In [4]:
import numpy as np
from datascience import *

%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

In [6]:
def triple(x):
    return 3 * x

In [7]:
triple(3)

9

In [9]:
triple('ha')

'hahaha'

In [10]:
triple(make_array(1,2,3))

array([3, 6, 9])

In [11]:
triple(np.arange(3,15,3))

array([ 9, 18, 27, 36])

In [15]:
def percent_of_total(s):
    return np.round(s / sum(s) * 100, 2)

In [16]:
percent_of_total(np.arange(3,15,3))

array([ 10.,  20.,  30.,  40.])

In [18]:
def hypotenuse(x, y):
    return (x**2 + y**2) ** .5

In [19]:
hypotenuse(9,12)

15.0

### Function to return age given a year

In [35]:
def age(year):
    age = 2026 - year
    return age

In [36]:
age(1942)

84

In [43]:
def name_and_age(name, year):
    '''
    Returns a string with name and age of person.
    Arguements:
            name: name of the person
            year: year the person was born
    returns:
        string with name and age
    '''
    return name + ' is ' + str(age(year)) + ' years old.'

In [44]:
name_and_age('noah', 2004)

'noah is 22 years old.'

In [45]:
ages = Table().with_columns(
    'person', make_array('jim', 'pam', 'joe', 'mary'),
    'birth year', make_array(1985, 1988, 1967, 1904)
)
ages

person | birth year
jim    | 1985
pam    | 1988
joe    | 1967
mary   | 1904

In [46]:
ages.apply(name_and_age, 'person', 'birth year')

array(['jim is 41 years old.', 'pam is 38 years old.',
       'joe is 59 years old.', 'mary is 122 years old.'],
      dtype='<U22')

In [47]:
ages.apply(age, 'birth year')

array([ 41,  38,  59, 122])

In [48]:
name_and_age?

Signature: name_and_age(name, year)
Docstring:
Returns a string with name and age of person.
Arguements:
        name: name of the person
        year: year the person was born
returns:
    string with name and age
File:      c:\users\s02881700\appdata\local\temp\ipykernel_17172\3020493007.py
Type:      function

# Groups

In [50]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [51]:
cones.group('Flavor')

Flavor     | count
bubblegum  | 1
chocolate  | 3
strawberry | 2

In [52]:
cones.group('Flavor', np.average)

Flavor     | Color average | Price average
bubblegum  |               | 4.75
chocolate  |               | 5.08333
strawberry |               | 4.4

In [53]:
cones.drop('Color').group('Flavor', np.average)

Flavor     | Price average
bubblegum  | 4.75
chocolate  | 5.08333
strawberry | 4.4

In [54]:
cones = cones.drop('Color')

In [55]:
cones

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [58]:
cones.group('Flavor', min)

Flavor     | Price min
bubblegum  | 4.75
chocolate  | 4.75
strawberry | 3.55

In [59]:
cones.group('Flavor', list)

Flavor     | Price list
bubblegum  | [4.75]
chocolate  | [4.75, 5.25, 5.25]
strawberry | [3.5499999999999998, 5.25]

## Cross-classify with two-group columns

In [61]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [62]:
cones.group(['Flavor', 'Color'])

Flavor     | Color       | count
bubblegum  | pink        | 1
chocolate  | dark brown  | 2
chocolate  | light brown | 1
strawberry | pink        | 2

In [63]:
cones.group(['Flavor', 'Color'], np.average)

Flavor     | Color       | Price average
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
strawberry | pink        | 4.4

In [64]:
cones.group(['Flavor', 'Color'], list)

Flavor     | Color       | Price list
bubblegum  | pink        | [4.75]
chocolate  | dark brown  | [5.25, 5.25]
chocolate  | light brown | [4.75]
strawberry | pink        | [3.5499999999999998, 5.25]