# Tables, Columdns, and Rows

In [1]:
import numpy as np
from datascience import *

In [2]:
nba = Table.read_table('nba_salaries.csv')
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [3]:
nba.show(5)

In [4]:
nba.num_rows

9456

In [5]:
nba.num_columns

6

In [6]:
nba.labels

('rank', 'name', 'position', 'team', 'salary', 'season')

In [7]:
#getting the players only in the 2024 season, selecting the row with .where
nba = nba.where('season', 2020).drop('seasons')

In [8]:
warriors = nba.where('team', 'Golden State Warriors')
warriors

rank | name                | position | team                  | salary   | season
1    | Stephen Curry       | PG       | Golden State Warriors | 40231758 | 2020
13   | Klay Thompson       | SG       | Golden State Warriors | 32742000 | 2020
60   | Draymond Green      | PF       | Golden State Warriors | 18539130 | 2020
223  | Kevon Looney        | PF       | Golden State Warriors | 4464226  | 2020
316  | Willie Cauley-Stein | C        | Golden State Warriors | 2177483  | 2020
332  | Jordan Poole        | SG       | Golden State Warriors | 1964760  | 2020
339  | Omari Spellman      | PF       | Golden State Warriors | 1897800  | 2020
496  | Alen Smailagic      | PF       | Golden State Warriors | 898310   | 2020
497  | Eric Paschall       | PF       | Golden State Warriors | 898310   | 2020
502  | Damion Lee          | SG       | Golden State Warriors | 842327   | 2020
... (3 rows omitted)

In [9]:
nba.where('team', 'Golden State Warriors').where('rank', are.below(15))

rank | name          | position | team                  | salary   | season
1    | Stephen Curry | PG       | Golden State Warriors | 40231758 | 2020
13   | Klay Thompson | SG       | Golden State Warriors | 32742000 | 2020

In [10]:
warriors = warriors.relabeled('salary','$')

In [11]:
warriors

rank | name                | position | team                  | $        | season
1    | Stephen Curry       | PG       | Golden State Warriors | 40231758 | 2020
13   | Klay Thompson       | SG       | Golden State Warriors | 32742000 | 2020
60   | Draymond Green      | PF       | Golden State Warriors | 18539130 | 2020
223  | Kevon Looney        | PF       | Golden State Warriors | 4464226  | 2020
316  | Willie Cauley-Stein | C        | Golden State Warriors | 2177483  | 2020
332  | Jordan Poole        | SG       | Golden State Warriors | 1964760  | 2020
339  | Omari Spellman      | PF       | Golden State Warriors | 1897800  | 2020
496  | Alen Smailagic      | PF       | Golden State Warriors | 898310   | 2020
497  | Eric Paschall       | PF       | Golden State Warriors | 898310   | 2020
502  | Damion Lee          | SG       | Golden State Warriors | 842327   | 2020
... (3 rows omitted)

In [12]:
salaries = warriors.select('$')
salaries

$
40231758
32742000
18539130
4464226
2177483
1964760
1897800
898310
898310
842327
... (3 rows omitted)

In [13]:
type(salaries)

datascience.tables.Table

In [14]:
type(warriors.column('$'))

numpy.ndarray

In [15]:
np.sum(warriors.column('$'))

106010951

In [16]:
np.max(warriors.column('$'))

40231758

In [17]:
sal = warriors.column('$')
sal.max()

40231758

In [18]:
warriors.show()

In [19]:
warriors.show(warriors.num_rows)

In [20]:
np.max?

Signature:
np.max(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.max(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function max at 0x000002BAEE734880>
File:            c:\users\s02881700\miniconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:
Return the maximum of an array or maximum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used. If this is a tuple of ints, the maximum is selected over
    multiple axes, instead of a single axis or all the axes as before.

out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See :ref:`ufuncs-output-type` for more details.

keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the input array.

    If the default value is passed, then `keepdims` will not be
    passed through to the ``max`` method of sub-classes of
    `ndarray`, however any non-default value will be.  If the
    sub-class' method does not implement `keepdims` any
    exceptions will be raised.

initial : scalar, optional
    The minimum value of an output element. Must be present to allow
    computation on empty slice. See `~numpy.ufunc.reduce` for details.

where : array_like of bool, optional
    Elements to compare for the maximum. See `~numpy.ufunc.reduce`
    for details.

Returns
-------
max : ndarray or scalar
    Maximum of `a`. If `axis` is None, the result is a scalar value.
    If `axis` is an int, the result is an array of dimension
    ``a.ndim - 1``. If `axis` is a tuple, the result is an array of
    dimension ``a.ndim - len(axis)``.

See Also
--------
min :
    The minimum value of an array along a given axis, propagating any NaNs.
nanmax :
    The maximum value of an array along a given axis, ignoring any NaNs.
maximum :
    Element-wise maximum of two arrays, propagating any NaNs.
fmax :
    Element-wise maximum of two arrays, ignoring any NaNs.
argmax :
    Return the indices of the maximum values.

nanmin, minimum, fmin

Notes
-----
NaN values are propagated, that is if at least one item is NaN, the
corresponding max value will be NaN as well. To ignore NaN values
(MATLAB behavior), please use nanmax.

Don't use `~numpy.max` for element-wise comparison of 2 arrays; when
``a.shape[0]`` is 2, ``maximum(a[0], a[1])`` is faster than
``max(a, axis=0)``.

Examples
--------
>>> import numpy as np
>>> a = np.arange(4).reshape((2,2))
>>> a
array([[0, 1],
       [2, 3]])
>>> np.max(a)           # Maximum of the flattened array
3
>>> np.max(a, axis=0)   # Maxima along the first axis
array([2, 3])
>>> np.max(a, axis=1)   # Maxima along the second axis
array([1, 3])
>>> np.max(a, where=[False, True], initial=-1, axis=0)
array([-1,  3])
>>> b = np.arange(5, dtype=np.float64)
>>> b[2] = np.nan
>>> np.max(b)
np.float64(nan)
>>> np.max(b, where=~np.isnan(b), initial=-1)
4.0
>>> np.nanmax(b)
4.0

You can use an initial value to compute the maximum of an empty slice, or
to initialize it to a different value:

>>> np.max([[-50], [10]], axis=-1, initial=0)
array([ 0, 10])

Notice that the initial value is used as one of the elements for which the
maximum is determined, unlike for the default argument Python's max
function, which is only used for empty iterables.

>>> np.max([5], initial=6)
6
>>> max([5], default=6)
5
Class docstring:
Class to wrap functions with checks for __array_function__ overrides.

All arguments are required, and can only be passed by position.

Parameters
----------
dispatcher : function or None
    The dispatcher function that returns a single sequence-like object
    of all arguments relevant.  It must have the same signature (except
    the default values) as the actual implementation.
    If ``None``, this is a ``like=`` dispatcher and the
    ``_ArrayFunctionDispatcher`` must be called with ``like`` as the
    first (additional and positional) argument.
implementation : function
    Function that implements the operation on NumPy arrays without
    overrides.  Arguments passed calling the ``_ArrayFunctionDispatcher``
    will be forwarded to this (and the ``dispatcher``) as if using
    ``*args, **kwargs``.

Attributes
----------
_implementation : function
    The original implementation passed in.

In [21]:
warriors.select('name', '$')

name                | $
Stephen Curry       | 40231758
Klay Thompson       | 32742000
Draymond Green      | 18539130
Kevon Looney        | 4464226
Willie Cauley-Stein | 2177483
Jordan Poole        | 1964760
Omari Spellman      | 1897800
Alen Smailagic      | 898310
Eric Paschall       | 898310
Damion Lee          | 842327
... (3 rows omitted)

In [22]:
nba.column('season').max()

2020

In [23]:
nba.sort('season', descending=True)

rank | name              | position | team                  | salary   | season
1    | Stephen Curry     | PG       | Golden State Warriors | 40231758 | 2020
2    | Chris Paul        | PG       | Oklahoma City Thunder | 38506482 | 2020
3    | Russell Westbrook | PG       | Houston Rockets       | 38506482 | 2020
4    | John Wall         | PG       | Washington Wizards    | 38199000 | 2020
5    | Kevin Durant      | SF       | Brooklyn Nets         | 38199000 | 2020
6    | James Harden      | SG       | Houston Rockets       | 38199000 | 2020
7    | LeBron James      | SF       | Los Angeles Lakers    | 37436858 | 2020
8    | Kyle Lowry        | PG       | Toronto Raptors       | 34996296 | 2020
9    | Blake Griffin     | PF       | Detroit Pistons       | 34449964 | 2020
10   | Tobias Harris     | SF       | Philadelphia 76ers    | 32742000 | 2020
... (518 rows omitted)

# Ranges

In [24]:
make_array(0,1,2,3,4,5,6)

array([0, 1, 2, 3, 4, 5, 6])

In [25]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [26]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [27]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.arange(0,1,.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

# Rows

In [29]:
warriors.take(1)

rank | name          | position | team                  | $        | season
13   | Klay Thompson | SG       | Golden State Warriors | 32742000 | 2020

In [30]:
warriors.take(0,1,4)

rank | name                | position | team                  | $        | season
1    | Stephen Curry       | PG       | Golden State Warriors | 40231758 | 2020
13   | Klay Thompson       | SG       | Golden State Warriors | 32742000 | 2020
316  | Willie Cauley-Stein | C        | Golden State Warriors | 2177483  | 2020

In [31]:
warriors.take(np.arange(5))

rank | name                | position | team                  | $        | season
1    | Stephen Curry       | PG       | Golden State Warriors | 40231758 | 2020
13   | Klay Thompson       | SG       | Golden State Warriors | 32742000 | 2020
60   | Draymond Green      | PF       | Golden State Warriors | 18539130 | 2020
223  | Kevon Looney        | PF       | Golden State Warriors | 4464226  | 2020
316  | Willie Cauley-Stein | C        | Golden State Warriors | 2177483  | 2020

In [32]:
warriors.take(np.arange(0,5))

rank | name                | position | team                  | $        | season
1    | Stephen Curry       | PG       | Golden State Warriors | 40231758 | 2020
13   | Klay Thompson       | SG       | Golden State Warriors | 32742000 | 2020
60   | Draymond Green      | PF       | Golden State Warriors | 18539130 | 2020
223  | Kevon Looney        | PF       | Golden State Warriors | 4464226  | 2020
316  | Willie Cauley-Stein | C        | Golden State Warriors | 2177483  | 2020

In [33]:
warriors.take(np.arange(5)).column('$').sum()

98154597

In [34]:
warriors.select('rank', 'name')

rank | name
1    | Stephen Curry
13   | Klay Thompson
60   | Draymond Green
223  | Kevon Looney
316  | Willie Cauley-Stein
332  | Jordan Poole
339  | Omari Spellman
496  | Alen Smailagic
497  | Eric Paschall
502  | Damion Lee
... (3 rows omitted)

In [35]:
warriors.select(0,1)

rank | name
1    | Stephen Curry
13   | Klay Thompson
60   | Draymond Green
223  | Kevon Looney
316  | Willie Cauley-Stein
332  | Jordan Poole
339  | Omari Spellman
496  | Alen Smailagic
497  | Eric Paschall
502  | Damion Lee
... (3 rows omitted)

In [36]:
warriors.select(np.arange(0,2))

rank | name
1    | Stephen Curry
13   | Klay Thompson
60   | Draymond Green
223  | Kevon Looney
316  | Willie Cauley-Stein
332  | Jordan Poole
339  | Omari Spellman
496  | Alen Smailagic
497  | Eric Paschall
502  | Damion Lee
... (3 rows omitted)

# Ways to create a table

## creating a table from scratch

In [37]:
#creating columns
streets = make_array('Harmony', 'Horsetooth', 'drake', 'prospect')
streets

array(['Harmony', 'Horsetooth', 'drake', 'prospect'],
      dtype='<U10')

In [38]:
south = Table().with_columns('street name', streets)
south

street name
Harmony
Horsetooth
drake
prospect

In [39]:
type(south)

datascience.tables.Table

In [40]:
type(streets)

numpy.ndarray

In [41]:
south=south.with_column('blocks from campus', np.arange(0,4))
south

street name | blocks from campus
Harmony     | 0
Horsetooth  | 1
drake       | 2
prospect    | 3

In [42]:
south = south.with_row(['Mulburry', 5])
south

street name | blocks from campus
Harmony     | 0
Horsetooth  | 1
drake       | 2
prospect    | 3
Mulburry    | 5

In [43]:
south = south.with_column('blocks from campus', np.where(south.column('street name') == 'Harmony', 4, south.column('blocks from campus'))
)
south

street name | blocks from campus
Harmony     | 4
Horsetooth  | 1
drake       | 2
prospect    | 3
Mulburry    | 5

In [44]:
south=south.with_column('city', 'Fort Collins')

In [45]:
south

street name | blocks from campus | city
Harmony     | 4                  | Fort Collins
Horsetooth  | 1                  | Fort Collins
drake       | 2                  | Fort Collins
prospect    | 3                  | Fort Collins
Mulburry    | 5                  | Fort Collins

## Accessing a cell in a table

In [48]:
south

street name | blocks from campus | city
Harmony     | 4                  | Fort Collins
Horsetooth  | 1                  | Fort Collins
drake       | 2                  | Fort Collins
prospect    | 3                  | Fort Collins
Mulburry    | 5                  | Fort Collins

In [52]:
south.column('blocks from campus').item(4)

5

In [53]:
south.row(4).item('blocks from campus')

5

In [56]:
south.where('street name', 'Mulburry').take(0)['blocks from campus'].item(0)

5

In [58]:
south.row(4).item(1)

5

## Changing the value in a cell

In [59]:
blocks = south.column('blocks from campus').copy()
blocks[4] = 8
south = south.with_column('blocks from campus', blocks)

In [60]:
south

street name | blocks from campus | city
Harmony     | 4                  | Fort Collins
Horsetooth  | 1                  | Fort Collins
drake       | 2                  | Fort Collins
prospect    | 3                  | Fort Collins
Mulburry    | 8                  | Fort Collins