In [1]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

In [2]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [4]:
cones.group('Flavor')

Flavor     | count
bubblegum  | 1
chocolate  | 3
strawberry | 2

In [5]:
cones.group('Flavor', np.average)

Flavor     | Color average | Price average
bubblegum  |               | 4.75
chocolate  |               | 5.08333
strawberry |               | 4.4

In [6]:
cones.select('Flavor', 'Price').group('Flavor', collect=np.average)

Flavor     | Price average
bubblegum  | 4.75
chocolate  | 5.08333
strawberry | 4.4

In [7]:
cones.select('Flavor', 'Price').group('Flavor', collect=min)

Flavor     | Price min
bubblegum  | 4.75
chocolate  | 4.75
strawberry | 3.55

## Cross classify with two-group columns

In [9]:
cones.group(['Flavor', 'Color'])

Flavor     | Color       | count
bubblegum  | pink        | 1
chocolate  | dark brown  | 2
chocolate  | light brown | 1
strawberry | pink        | 2

In [11]:
cones.group(['Flavor', 'Color'], collect=np.average)

Flavor     | Color       | Price average
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
strawberry | pink        | 4.4

In [16]:
cones = cones.with_rows([
['vanilla', 'pale yellow', 3.89],
['vanilla', 'green', 5.00]
])
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75
vanilla    | pale yellow | 3.89
vanilla    | green       | 5

## Cross-classify with pivot

In [17]:
cones.pivot('Flavor', 'Color')

Color       | bubblegum | chocolate | strawberry | vanilla
dark brown  | 0         | 2         | 0          | 0
green       | 0         | 0         | 0          | 1
light brown | 0         | 1         | 0          | 0
pale yellow | 0         | 0         | 0          | 1
pink        | 1         | 0         | 2          | 0

In [18]:
cones.pivot('Flavor', 'Color', 'Price', collect=np.average)

Color       | bubblegum | chocolate | strawberry | vanilla
dark brown  | 0         | 5.25      | 0          | 0
green       | 0         | 0         | 0          | 5
light brown | 0         | 4.75      | 0          | 0
pale yellow | 0         | 0         | 0          | 3.89
pink        | 4.75      | 0         | 4.4        | 0

## Group or Pivot?

In [19]:
skyscrapers = Table.read_table('skyscrapers.csv')
skyscrapers

name                              | material        | city          | height | completed
One World Trade Center            | mixed/composite | New York City | 541.3  | 2014
Willis Tower                      | steel           | Chicago       | 442.14 | 1974
432 Park Avenue                   | concrete        | New York City | 425.5  | 2015
Trump International Hotel & Tower | concrete        | Chicago       | 423.22 | 2009
Empire State Building             | steel           | New York City | 381    | 1931
Bank of America Tower             | mixed/composite | New York City | 365.8  | 2009
Stratosphere Tower                | concrete        | Las Vegas     | 350.22 | 1996
Aon Center                        | steel           | Chicago       | 346.26 | 1973
John Hancock Center               | steel           | Chicago       | 343.69 | 1969
Chrysler Building                 | steel           | New York City | 318.9  | 1930
... (1771 rows omitted)

**task**: for each city, find the tallest building per material

In [25]:
skyscrapers.pivot('material', 'city', 'height', collect=max)

city       | concrete | mixed/composite | steel
Atlanta    | 264.25   | 311.8           | 169.47
Austin     | 208.15   | 0               | 93.6
Baltimore  | 161.24   | 0               | 155.15
Boston     | 121.92   | 139             | 240.79
Charlotte  | 265.48   | 239.7           | 179.23
Chicago    | 423.22   | 306.94          | 442.14
Cincinnati | 125      | 202.69          | 175
Cleveland  | 125      | 288.65          | 215.8
Columbus   | 79.25    | 0               | 169.3
Dallas     | 176.48   | 280.72          | 270.06
... (25 rows omitted)

In [31]:
def take_first(a):
    return a.item(0)

sky_pivot = (skyscrapers.sort('height', descending=True).pivot('material', 'city', values='name', collect=take_first))
sky_pivot

city       | concrete                          | mixed/composite                           | steel
Atlanta    | SunTrust Plaza                    | Bank of America Plaza                     | State of Georgia Building
Austin     | The Austonian                     |                                           | University of Texas Tower
Baltimore  | Legg Mason Building               |                                           | Bank of America Building
Boston     | Harbor Towers I                   | Atlantic Wharf                            | 200 Clarendon
Charlotte  | Bank of America Corporate Center  | Duke Energy Center                        | One Wells Fargo Center
Chicago    | Trump International Hotel & Tower | The Franklin - North Tower                | Willis Tower
Cincinnati | Chemed Center                     | Great American Tower at Queen City Square | Carew Tower
Cleveland  | National City Center              | Key Tower                                 | Terminal Tower
Columbus   | Lincoln Tower                     |                                           | Leveque Tower
Dallas     | Ross Tower                        | Bank of America Plaza                     | Renaissance Tower
... (25 rows omitted)

In [43]:
skyscrapers.sort('height', descending=True ).select('material', 'city', 'height', 'name').group(['city', 'material'], take_first)

city      | material        | height take_first | name take_first
Atlanta   | concrete        | 264.25            | SunTrust Plaza
Atlanta   | mixed/composite | 311.8             | Bank of America Plaza
Atlanta   | steel           | 169.47            | State of Georgia Building
Austin    | concrete        | 208.15            | The Austonian
Austin    | steel           | 93.6              | University of Texas Tower
Baltimore | concrete        | 161.24            | Legg Mason Building
Baltimore | steel           | 155.15            | Bank of America Building
Boston    | concrete        | 121.92            | Harbor Towers I
Boston    | mixed/composite | 139               | Atlantic Wharf
Boston    | steel           | 240.79            | 200 Clarendon
... (81 rows omitted)

In [35]:
skyscrapers.group?

Signature: skyscrapers.group(column_or_label, collect=None)
Docstring:
Group rows by unique values in a column; count or aggregate others.

Args:
    ``column_or_label``: values to group (column label or index, or array)

    ``collect``: a function applied to values in other columns for each group

Returns:
    A Table with each row corresponding to a unique value in ``column_or_label``,
    where the first column contains the unique values from ``column_or_label``, and the
    second contains counts for each of the unique values. If ``collect`` is
    provided, a Table is returned with all original columns, each containing values
    calculated by first grouping rows according to ``column_or_label``, then applying
    ``collect`` to each set of grouped values in the other columns.

Note:
    The grouped column will appear first in the result table. If ``collect`` does not
    accept arguments with one of the column types, that column will be empty in the resulting
    table.

>>> marbles = Table().with_columns(
...    "Color", make_array("Red", "Green", "Blue", "Red", "Green", "Green"),
...    "Shape", make_array("Round", "Rectangular", "Rectangular", "Round", "Rectangular", "Round"),
...    "Amount", make_array(4, 6, 12, 7, 9, 2),
...    "Price", make_array(1.30, 1.30, 2.00, 1.75, 1.40, 1.00))
>>> marbles
Color | Shape       | Amount | Price
Red   | Round       | 4      | 1.3
Green | Rectangular | 6      | 1.3
Blue  | Rectangular | 12     | 2
Red   | Round       | 7      | 1.75
Green | Rectangular | 9      | 1.4
Green | Round       | 2      | 1
>>> marbles.group("Color") # just gives counts
Color | count
Blue  | 1
Green | 3
Red   | 2
>>> marbles.group("Color", max) # takes the max of each grouping, in each column
Color | Shape max   | Amount max | Price max
Blue  | Rectangular | 12         | 2
Green | Round       | 9          | 1.4
Red   | Round       | 7          | 1.75
>>> marbles.group("Shape", sum) # sum doesn't make sense for strings
Shape       | Color sum | Amount sum | Price sum
Rectangular |           | 27         | 4.7
Round       |           | 13         | 4.05
File:      c:\users\s02881700\miniconda3\lib\site-packages\datascience\tables.py
Type:      method

In [42]:
skyscrapers.where('city', 'Austin').sort('height', descending=True)

name                           | material | city   | height | completed
The Austonian                  | concrete | Austin | 208.15 | 2010
360 Condominiums               | concrete | Austin | 177.1  | 2008
Frost Bank Tower               | concrete | Austin | 157.2  | 2004
W Austin Hotel & Residences    | concrete | Austin | 145.27 | 2010
Spring                         | concrete | Austin | 132.29 | 2009
The Bowie                      | concrete | Austin | 128.9  | 2015
Ashton                         | concrete | Austin | 125.5  | 2009
JW Marriott Convention Hotel   | concrete | Austin | 124.4  | 2015
Four Seasons Residences Austin | concrete | Austin | 122.25 | 2010
One American Center            | concrete | Austin | 122.22 | 1984
... (7 rows omitted)

**Task:** for each city find the height difference between the talles steel building and the tallest concrete building

In [53]:
skyscrapers.select('city', 'material', 'height').group(['city', 'material'], max)

city      | material        | height max
Atlanta   | concrete        | 264.25
Atlanta   | mixed/composite | 311.8
Atlanta   | steel           | 169.47
Austin    | concrete        | 208.15
Austin    | steel           | 93.6
Baltimore | concrete        | 161.24
Baltimore | steel           | 155.15
Boston    | concrete        | 121.92
Boston    | mixed/composite | 139
Boston    | steel           | 240.79
... (81 rows omitted)

In [57]:
sky_pivot = skyscrapers.select('city', 'material', 'height').pivot('material', 'city', 'height', max)
sky_pivot

city       | concrete | mixed/composite | steel
Atlanta    | 264.25   | 311.8           | 169.47
Austin     | 208.15   | 0               | 93.6
Baltimore  | 161.24   | 0               | 155.15
Boston     | 121.92   | 139             | 240.79
Charlotte  | 265.48   | 239.7           | 179.23
Chicago    | 423.22   | 306.94          | 442.14
Cincinnati | 125      | 202.69          | 175
Cleveland  | 125      | 288.65          | 215.8
Columbus   | 79.25    | 0               | 169.3
Dallas     | 176.48   | 280.72          | 270.06
... (25 rows omitted)

In [59]:
sky_pivot = sky_pivot.with_column('difference', abs(sky_pivot.column('steel') - sky_pivot.column('concrete')))
sky_pivot

city       | concrete | mixed/composite | steel  | difference
Atlanta    | 264.25   | 311.8           | 169.47 | 94.78
Austin     | 208.15   | 0               | 93.6   | 114.55
Baltimore  | 161.24   | 0               | 155.15 | 6.09001
Boston     | 121.92   | 139             | 240.79 | 118.87
Charlotte  | 265.48   | 239.7           | 179.23 | 86.25
Chicago    | 423.22   | 306.94          | 442.14 | 18.92
Cincinnati | 125      | 202.69          | 175    | 50
Cleveland  | 125      | 288.65          | 215.8  | 90.8
Columbus   | 79.25    | 0               | 169.3  | 90.05
Dallas     | 176.48   | 280.72          | 270.06 | 93.58
... (25 rows omitted)

## Joins

In [69]:
full = Table.read_table('nc-est2019-agesex-res.csv')
census = full.select('SEX', 'AGE', 'POPESTIMATE2019')
census

SEX  | AGE  | POPESTIMATE2019
0    | 0    | 3783052
0    | 1    | 3829599
0    | 2    | 3922044
0    | 3    | 3998665
0    | 4    | 4043323
0    | 5    | 4028281
0    | 6    | 4017227
0    | 7    | 4022319
0    | 8    | 4066194
0    | 9    | 4061874
... (296 rows omitted)

In [70]:
census.group('SEX')

SEX  | count
0    | 102
1    | 102
2    | 102

In [67]:
sex_codes = Table().with_columns(
    'SEX CODE', make_array(0,1,2),
    'SEX descriptor', make_array('All', 'Male', 'Female')
)
sex_codes

SEX CODE | SEX descriptor
0        | All
1        | Male
2        | Female

In [72]:
census.join('SEX', sex_codes, 'SEX CODE').sort('AGE')

SEX  | AGE  | POPESTIMATE2019 | SEX descriptor
0    | 0    | 3783052         | All
1    | 0    | 1935117         | Male
2    | 0    | 1847935         | Female
0    | 1    | 3829599         | All
1    | 1    | 1958585         | Male
2    | 1    | 1871014         | Female
0    | 2    | 3922044         | All
1    | 2    | 2005544         | Male
2    | 2    | 1916500         | Female
0    | 3    | 3998665         | All
... (296 rows omitted)